// apps/solid-host/src/App.tsx
import type { Component } from 'solid-js';
import { lazy, Suspense } from 'solid-js';
import { Route, A, Router } from '@solidjs/router';
// import { SolidRemote } from 'solid-remote/SolidRemote';
// import { ReactRemote } from 'react-remote/ReactRemote';
const SolidRemote = lazy(() => import('solid-remote/SolidRemote'));

const App: Component = () => (
  <div>
    <h1>SolidJS Host</h1>
    <Router>
      <Route path="/" component={Home} />
      <Route path="/solid" component={Layout} />
      {/* <Route path="/react" component={ReactRemote} /> */}
    </Router>
  </div>
);
export default App;

const Home: Component = () => (
  <>
    <nav>
      <A href="/">Home</A> | <A href="/solid">Solid Remote</A> |{' '}
    </nav>
    <p>Welcome to Solid Host</p>
  </>
);

const Layout: Component = () => (
  <>
    <nav>
      <A href="/">Home</A> | <A href="/solid">Solid Remote</A> |{' '}
    </nav>
    <Suspense fallback={<div>Loading...</div>}>
      <SolidRemote label="Button" />
    </Suspense>
  </>
);

// apps/react-host/src/app/app.tsx
import * as React from 'react';
import NxWelcome from './nx-welcome';
import { Link, Route, Routes } from 'react-router-dom';

export function App() {
  return (
    <React.Suspense fallback={null}>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
      </ul>
      <Routes>
        <Route path="/" element={<NxWelcome title="react-host" />} />
      </Routes>
    </React.Suspense>
  );
}

export default App;
